const     Lenovo = [
{
    indexValue : 1,
    title:
      "Lenovo Legion Y530 Core i5 8th Gen - (8 GB/1 TB HDD/Windows 10 Home/4 GB Graphics) Y530-15ICH Gaming Laptop\xa0\xa0(15.6 inch, Raven Black, 2.3 kg)",
    rating: "4.2",
    reviews: "55 Ratings\xa0&\xa014 Reviews",
    specialDiscount: "Extra ₹32400 discount",
    sellingPrice: "₹49,990",
    scratchedPrice: "₹82,390",
    discountPercentage: "39% off",
    description:
      "Play graphics-rich games seamlessly on this Lenovo gaming laptop. Powered by the NVIDIA GeForce GTX 1050 (4 GB GDDR5) graphics and the Intel Core i5-8300H processor, this laptop facilitates a glitch-free and fuss-free gaming experience.",
    Brands: "Lenovo",
    highlightsList: [
      "NVIDIA Geforce GTX 1050 for Desktop Level Performance",
      "15.6 inch Full HD LED Backlit Anti-glare IPS Display",
      "Light Laptop without Optical Disk Drive",
      "Pre-installed Genuine Windows 10 OS"
    ],
    Specification: {
      Brands: "Lenovo",
      "Sales Package": "Laptop, Power Adaptor, User Guide, Warranty Documents",
      "Model Number": "Y530-15ICH",
      "Part Number": "81FV005VIN",
      Series: "Legion Y530",
      Color: "Raven Black",
      Type: "Gaming Laptop",
      "Suitable For": "Processing & Multitasking, Gaming",
      "Battery Backup": "Upto 9 hours",
      "Power Supply": "135 W AC Adapter",
      "Battery Cell": "3 cell",
      "MS Office Provided": "No",
      "Dedicated Graphic Memory Type": "GDDR5",
      "Dedicated Graphic Memory Capacity": "4 GB",
      ProcessorBrand: "Intel",
      ProcessorName: "Core i5",
      "Processor Generation": "8th Gen",
      SSD: "No",
      RAM: "8 GB",
      RAMType: "DDR4",
      HDDCapacity: "1 TB",
      "Processor Variant": "8300H",
      "Clock Speed": "2.3 GHz with Turbo Boost Upto 4 GHz",
      "Expandable Memory": "Upto 16 GB",
      Cache: "8 MB",
      RPM: "7200",
      GraphicProcessor: "NVIDIA Geforce GTX 1050",
      "Number of Cores": "4",
      "OS Architecture": "64 bit",
      OperatingSystem: "Windows 10 Home",
      "System Architecture": "64 bit",
      "Mic In": "Yes",
      RJ45: "Yes",
      "USB Port": "3 x USB 3.1, 1 x USB Type C",
      "HDMI Port": "1 x HDMI Port (v2.0)",
      Touchscreen: "No",
      "Screen Size": "39.62 cm (15.6 inch)",
      "Screen Resolution": "1920 x 1080 Pixel",
      "Screen Type": "Full HD LED Backlit Anti-glare IPS Display",
      Speakers: "Built-in Dual Speakers",
      "Internal Mic": "Built-in Microphones",
      "Sound Properties": "2 x 2 W Stereo Speakers with Dolby Atmos",
      "Wireless LAN": "WIFI 2x2 AC",
      Bluetooth: "v4.1",
      Ethernet: "100/1000 Mbps",
      Dimensions: "360 x 267 x 24.2 mm",
      Weight: "2.3 kg",
      "Disk Drive": "Not Available",
      "Web Camera": "HD 720P Webcam",
      Antivirus: "McAfee LiveSafe 12 Months Subscription",
      Keyboard: "White Color Backlit Keyboard",
      "Backlit Keyboard": "Yes",
      "Pointer Device": "Multi Gesture Touchpad",
      "Included Software": "Lenovo App Explorer, Lenovo Companion 3.0",
      "Additional Features": "Li-ion Battery",
      "Warranty Summary": "1 Year Onsite Warranty",
      "Warranty Service Type": "Onsite",
      "Covered in Warranty": "Manufacturing Defects",
      "Not Covered in Warranty": "Physical Damage",
      "Domestic Warranty": "1 Year"
    },
    images: [
      "https://rukminim1.flixcart.com/image/352/352/jz7az680/computer/9/z/5/lenovo-na-gaming-laptop-original-imafj9wrn5zzj8mb.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/352/352/jz7az680/computer/9/z/5/lenovo-na-gaming-laptop-original-imafj9wrn5zzj8mb.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/352/352/jz7az680/computer/9/z/5/lenovo-na-gaming-laptop-original-imafj9wrn5zzj8mb.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/352/352/jz7az680/computer/9/z/5/lenovo-na-gaming-laptop-original-imafj9wrn5zzj8mb.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/352/352/jz7az680/computer/9/z/5/lenovo-na-gaming-laptop-original-imafj9wrn5zzj8mb.jpeg?q=70"
    ]
  }
];
export  default Lenovo;
